name: PRIME
favicon: null
layout_spectrum: 0.2493
typography_spectrum: 0.75343
title: Prime Soluções para Recuperação de Ativos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#828282'
    - '#363636'
    - '#b2b2b2'
    - '#1a1a1a'
    - '#eeeeee'
  brandStrength: 0.6783318517263979
  lightness: 0.23547468637116253
  saturation: 0.9988349985796958
  rhythmicContrast: 0.5962089609820396
purpose: []
